[FIX] openupgrade: Fix another AttributeError.
Since 12634e1227ab8446e34b747e02865f62087b5e86, `tools.safe_eval` is not the
module safe_eval but a function.

This commit fixes the following error:

```
Traceback (most recent call last):
  ...
  File "openupgrade/openerp/openupgrade/openupgrade_loading.py", line 55, in add_module_dependencies
    forced_deps = safe_eval.safe_eval(
AttributeError: 'function' object has no attribute 'safe_eval'
```